### ISSUE TITLE
Port of the theme for Visual Studio Code

### ISSUE THREAD

**Issue by tdeekens** [opattison/newbound-dark-syntax#3]
Thanks for this theme. I have been using it for at least a year now and loved it each day!

However, I am recently making the switch the VSCode. I was wondering if there was a way of migrating this theme to VSCode. Any tools or plans? Anything I could help with?

**Comment by opattison** [comment]
I don’t have plans to do that since I haven’t used VS Code. I imagine creating a port of it might be possible without too much work. If I do find myself using VS Code, I’ll certainly consider doing it myself.

But I did look into it and Sublime Text/TextMate themes are compatible with VS Code, so one could take the [yaml color scheme](https://github.com/opattison/newbound-dark-syntax/blob/master/colors.yml) and plug it into [base16builder](https://github.com/chriskempson/base16-builder/tree/master/templates) to output a compatible TextMate theme. That’s one of the reasons I created the base16-compatible scheme. That might serve as a stopgap or might even be all you need to use this palette with your preferred editor.

Feel free to give that a shot, or even create a custom theme like I did for Atom and I’ll accept a PR or link out to your work. Ports are absolutely fine – you can even use the name newbound if it’s substantially similar.
